### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by ayoubassis** [tw-yshuang/Git_SSH-Account_Switch#1]
I am using two github accounts on my laptop, say X & Y. I've been using X for sometime and everything was working perfectly well, but when I switched to Y and tried to push some commits, I got the following error:
```
remote: Permission to blurry-mood/NonMaxSuppression-with-Reinforcement-Learning.git denied to ayoub-assis.
fatal: unable to access 'https://github.com/blurry-mood/NonMaxSuppression-with-Reinforcement-Learning.git/': The requested URL returned error: 403
```

When I execute `git config --list`, it shows that I am effectively using the account X.
But my credentials ( `https://{username}:{token}@github.com` ), located inside `˜/.git-credentials` contain the Y's information.    
I'm wondering if this tool takes care of this too.

**Comment by tw-yshuang** [comment]
I think it can solve your problem well~~
I build this tool basic on `ssh-agent`, if you are interesting you can search about it.
There has one thing that you might care about it, this tool will automatically close your `ssh-agent` when you logout your OS account, it means that, if you are using this tool locally, all the `ssh-agent` will not close before you logout your OS or shutdown your laptop.
