### ISSUE TITLE
zsh, ahaha

### ISSUE THREAD

**Issue by adminka-root** [tw-yshuang/Git_SSH-Account_Switch#7]
zsh? Really?! Are you suggesting that I install zsh just for your script?! it's funny! Mister Naivety!

**Comment by tw-yshuang** [comment]
I already note that this tool is for `zsh`, because `bash` do not support autocomplete. It is welcome to give me some useful suggestions or find another solution. If you just want to be a hater at this open-source repository, you are just ridiculous🤣.

**Comment by adminka-root** [comment]
Here is my solution - https://github.com/adminka-root/git_switcher . I wrote this program yesterday. Do you know why? Because zsh is funny! xDDDDDDDDDDDDDD
P.S.:  And it's free too.

**Comment by tw-yshuang** [comment]
It is good to know that you contributed an open-source repository and also solved your problem, hope you can open your mind to praise with all the hard work open-source.👍🏻

**Comment by adminka-root** [comment]
Maybe I'm wrong, but. My mind is open to the idea that most of the open source projects exist not only thanks to the altruism of their owners. Let it be free, but. First, it can bring donations. Second, it can be part of a resume. Yes, open source projects make the world a better place. But their creators should not pretend to be the epitome of goodness and humanity. Because they are pursuing their own goals. Anyway... Well done for posting your project. This is beyond doubt. However, in my opinion, it was written in zsh not for the sake of people, but because it was more convenient to write you in zsh. It's not bad. Some people are even more comfortable that it's zsh. But for me, as a person who is too lazy to understand zsh and who is completely satisfied with bash, this did not seem convenient. And I was upset that there was no optimal alternative.

**Comment by tw-yshuang** [comment]
Great point. I created this repository and designed a convenient CLI command for myself, and also increase the community activity. Another important reason is I do not know how to use others' language to achieve `autocomplete` to interact with the terminal, that is why I use `zsh` script to code it. If you know how to do it, it is welcome to give me some advice or contribute.
