### ISSUE TITLE
Conflict with Conda - local:17: = not found

### ISSUE THREAD

**Issue by sutharsha** [tw-yshuang/Git_SSH-Account_Switch#9]
Getting the error local:17: = not found when conda is installed. 
Only when i comment out source $HOME/.git-acc from my profile does it stop. 

Setup:
Terminal : zsh
Device : Mac M1 Air 
OS: Ventura(13.4.1)

**Comment by tw-yshuang** [comment]
same issue with https://github.com/tw-yshuang/Git_SSH-Account_Switch/issues/5#issue-1382390511

**Comment by sutharsha** [comment]
Thx for the quick update. 
But there is no solution there to resolve it, only to use alternatives like pyenv/pipenv. 
The conflict with conda is blocker for me. 

Is there anyway i can help to resolve this?

p.s Awesome tool, resolved a lot of headaches for me.
